### ISSUE TITLE
More suggestion than issue..

### ISSUE THREAD

**Issue by kfanyo** [arielf/cuts#7]
Thank you! It's awesome to be able to stop futzing around with variable numbers of spaces.

What I found is that when you're accustomed to using 'cut' with cron, and programs run by cron, it's really easy to forget that 'cuts' is an external program and so requires the full path even when used together with cut. For example, this worked in cron:

<BLAH>=`ps x | grep <Blah>| grep -v grep | /usr/local/bin/cuts -3 | cut -d'\' -f1 | cut -d'_' -f2`

where

<BLAH>=`ps x | grep <Blah>| grep -v grep | cuts -3 | cut -d'\' -f1 | cut -d'_' -f2`

gave me a blank variable even though the program worked fine from the command line.

I scratched my head for an embarrassingly long time figuring out I'd left off the path.

Thanks again.

**Comment by arielf** [comment]
Thanks for the comment.

Did you know you can set up your preferred PATH in the crontab itself so you don't need to use full paths to commands?
Like this:

```
PATH=/usr/local/bin:/sbin:/bin:/usr/sbin:/usr/bin

# 
# more crontab vars & rules come here...
#
```
